baseurl = "/"
canonifyURLs = true
disqusShortname = "shortname"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Hugo Future Imperfect"
[[menu.main]]
name = "登入"
url = "https://ryan-forestry-hugo.netlify.app/admin"
weight = 7
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 6
[[menu.main]]
identifier = "fa fa-sitemap"
name = "Categories"
url = "/categories/"
weight = 5
[[menu.main]]
identifier = "fa fa-list"
name = "Itemized"
url = "/itemized/"
weight = 4
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[params]
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
categoriesByCount = true
customCSS = ["default"]
customJS = ["default"]
description = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
disable_highlight = false
dynamicTitles = true
faviconVersion = ""
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "css"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
includeReadingTime = true
loadFavicon = false
navbarTitle = "Blog"
rssAppearAtBottom = true
rssAppearAtTop = false
showSidebarCategories = true
socialAppearAtBottom = true
socialAppearAtTop = false
socialShare = true
socialShareEmail = true
socialShareFacebook = true
socialShareGoogleplus = true
socialShareLinkedin = true
socialSharePinterest = true
socialShareReddit = true
socialShareStumbleupon = true
socialShareTwitter = true
viewMorePostLink = "/blog/"
[params.intro]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
header = "Ryan Chung"
paragraph = "偶爾爬山、偶爾攝影、偶爾龜在床上滾來滾去...<hr>這是一個測試用部落格"
[params.intro.pic]
alt = "Hugo Future Imperfect"
circle = true
imperfect = false
src = "/img/main/logo.jpg"
width = "200"
[params.postAmount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "ryanccj@gmail.com"
facebook = "ryan.chung.146"
flickr = ""
foursquare = ""
github = "RyanCCJ"
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "ryanccj"
jsfiddle = ""
linkedin = "example"
linkedin_company = ""
medium = ""
orcid = ""
pinterest = ""
qq = ""
quora = ""
reddit = ""
researchgate = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = ""
tumblr = ""
twitter = ""
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
